name: release
on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
    - uses: Songmu/tagpr@d1b8138b7a31075141b6cd64103de9485ced7ac9 # v1
      id: tagpr
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: haya14busa/action-update-semver@7d2c558640ea49e798d46539536190aff8c18715 # v1
      if: steps.tagpr.outputs.tag != ''
      with:
        tag: ${{ steps.tagpr.outputs.tag }}
