name: release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
    - uses: Songmu/tagpr@d1b8138b7a31075141b6cd64103de9485ced7ac9 # v1
      id: tagpr
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: haya14busa/action-update-semver@7d2c558640ea49e798d46539536190aff8c18715 # v1
      if: steps.tagpr.outputs.tag != ''
      with:
        tag: ${{ steps.tagpr.outputs.tag }}
