name: 'test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - run: |
          npm install
      - run: |
          npm run build && npm test
        env:
          PORT_BASE_URL: ${{ secrets.PORT_BASE_URL }}
          INPUT_BASEURL: ${{ secrets.PORT_BASE_URL }}
          INPUT_CLIENTID: ${{ secrets.PORT_CLIENT_ID }}
          INPUT_CLIENTSECRET: ${{ secrets.PORT_CLIENT_SECRET }}
