name: 'test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - run: |
          npm install
      - run: |
          npm run build && npm test
        env:
          PORT_BASE_URL: ${{ secrets.PORT_BASE_URL }}
          INPUT_BASEURL: ${{ secrets.PORT_BASE_URL }}
          INPUT_CLIENTID: ${{ secrets.PORT_CLIENT_ID }}
          INPUT_CLIENTSECRET: ${{ secrets.PORT_CLIENT_SECRET }}
